NA  Sequence_1
XX  
SP  Homo Sapiens
XX  
CL  1.1.4.0.0.
XX  
S1  MGDDRPFVCNAPGCGQRFTNEDHLAVHKHKHEMTLKFGPARTDSVIIADQTPTPTRFLKN
S1  CEEVGLFNELASSFEHEFKKAADEDEKKAAAGPLDMSLPSTPDIKIKEEEPVEVDSSPPD
S1  SPASSPCSPPLKEKEVTPKPVLISTPTPTIVRPGSLPLHLGYDPLHPTLPSPTSVITQAP
S1  PSNRQMGSPTGSLPLVMHLANGQTMPVLPGPPVQMPSVISLARPVSMVPNIPGIPGPPVN
S1  SSGSISPSGHPIPSEAKMRLKATLTHQVSSINGGCGMVVGTASTMVTARPEQSQILIQHP
S1  DAPSPAQPQVSPAQPTPSTGGRRRRTVDEDPDERRQRFLERNRAAASRCRQKRKLWVSSL
S1  EKKAEELTSQNIQLSNEVTLLRNEVAQLKQLLLAHKDCPVTALQKKTQGYLESPKESSEP
S1  TGSPAPVIQHSSATAPSNGLSVRSAAEAVATSVLTQMASQRTELSMPIQSHVIMTPQSQS
S1  AGR
XX  
FT  IPR004827    330	394
FT  IPR011616    332	391
