NA  T01963   Lim-3   P-Lim (mouse)   Xlim-3
XX
SP  clawed frog, Xenopus laevis
XX
RF  P36200
XX
CL  C0025; LIM-homeo; 3.1.3.1.5.
XX
S1  MLLERVRTGTQKSSDMCGYTGSPEIPQCAGCNQHIVDRFILKVLDRHWHSKCLKCNDCQI
S1  QLAEKCFSRGDSVYCKDDFFKRFGTKCAACQQGIPPTQVVRRAQEFVYHLHCFACIVCKR
S1  QLATGDEFYLMEDSRLVCKADYETAKQREAESTAKRPRTTITAKQLETLKNAYNNSPKPA
S1  RHVREQLSSETGLDMRVVQVWFQNRRAKEKRLKKDAGRQRWGQYFRNMKRSRGNSKSDKD
S1  SIQEEGPDSDAEVSFTDEPSMSEMNHSNGIYNSLNDSSPVLGRQAGSNGPFSLEHGGIPT
S1  QDQYHNLRSNSPYGIPQSPASLQSMPGHQSLLSNLAFPDTGLGIIGQGGQGVAPTMRVIG
S1  VNGPSSDLSTGSSGGYPDFPVSPASWLDEVDHTQF
XX
FT  PF00046   155   211
FT  P36200    154   213
FT  P36200    155   211
